name: Fix pydmx files

on:
  workflow_dispatch:

jobs:
  unpack:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Unzip pydmx files
        run: |
          ls -R -a
          cd meta-pydmx/recipes-pydmx/pydmx/files
          unzip Archiv.zip -d .

      - name: Commit changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add meta-pydmx/recipes-pydmx/pydmx/files
          git commit -m "Add pydmx files via GH Actions" || echo "No changes"
          git push
